project_mgmt_homepage:
    pattern:  /
    defaults: { _controller: ProjectMgmtBundle:Default:index }

book_show:
    pattern:  /book/{id}/show
    defaults: { _controller: "ProjectMgmtBundle:Book:show" }

book_new:
    pattern:  /book/new
    defaults: { _controller: "ProjectMgmtBundle:Book:new" }

book_create:
    pattern:  /book/create
    defaults: { _controller: "ProjectMgmtBundle:Book:create" }
    requirements: { _method: post }
    
chapter_show:
    pattern:  /chapter/{id}/show
    defaults: { _controller: "ProjectMgmtBundle:Chapter:show" }

chapter_new:
    pattern:  /chapter/{idBook}/new
    defaults: { _controller: "ProjectMgmtBundle:Chapter:new" }

chapter_create:
    pattern:  /chapter/{idBook}/create
    defaults: { _controller: "ProjectMgmtBundle:Chapter:create" }
    requirements: { _method: post }
    
chapter_update:
    pattern:  /chapter/{id}/update
    defaults: { _controller: "ProjectMgmtBundle:Chapter:update" }
    requirements: { _method: post }
    