parameters:
#    project_mgmt.example.class: ProjectMgmt\Bundle\Example

services:
#    project_mgmt.example:
#        class: %project_mgmt.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
