<?php

namespace ProjectMgmt\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends EntityRepository
{
    public function menuFindAll()
    {
        $query = $this
                    ->createQueryBuilder('b')
                    ->leftJoin('b.chapters', 'c')
                    ->addOrderBy('b.name', 'ASC')
        ;
        
        return $query->getQuery()->getResult();
    }
}
