
project_mgmt:
    resource: "@ProjectMgmtBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults: { _controller:ProjectMgmtBundle:Security:login }

#login_check:
#    pattern: /login_check

#logout: 
#    pattern: /logout

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
