security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
      fos_userbundle:
        id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: true
            form_login:
              always_use_default_target_path: true
              default_target_path: /
#              provider: fos_userbundle
#              csrf_provider: form.csrf_provider
            switch_user: true
            logout:
                path: fos_user_security_logout
                target: project_mgmt_homepage
                invalidate_session: false

    access_control:
        # Allow anonymous users to access login, login_check, and logout pages
        - { path: ^/login(_check)?, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/book/(new|create|organize), roles: ROLE_ADMIN }
        - { path: ^/json/book/update, roles: ROLE_ADMIN }
        - { path: ^/chapter/(new|create), roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
